name: Latest blog post workflow
on:
  schedule:  # Run workflow automatically
    - cron: '0 * * * *'  # Runs every hour, on the hour
  workflow_dispatch:  # Run workflow manually (without waiting for the cron to be called), through the GitHub Actions Workflow page directly
permissions:
  contents: write # To write the generated contents to the readme
  
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate blog post list
        run: |
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "BLOG-POST-LIST"
          readme_path: ./README.md
          max_post_count: "5"
          feed_list: "https://medium.com/feed/@davjroche"
      - name: Customize blog post template
        run: |
          echo "## Latest Medium Blog Posts\n" > blog_posts.md
          echo "| Title | Date |" >> blog_posts.md
          echo "|-------|------|" >> blog_posts.md
          cat ./README.md >> blog_posts.md
      - name: Update README with customized blog posts
        run: |
          cat blog_posts.md > ./README.md
